<?php
/* Smarty version 3.1.29, created on 2019-07-24 12:47:05
  from "wiki:Spray_common" */

if ($_smarty_tpl->smarty->ext->_validateCompiled->decodeProperties($_smarty_tpl, array (
  'has_nocache_code' => false,
  'version' => '3.1.29',
  'unifunc' => 'content_5d3837297acc10_49226086',
  'file_dependency' => 
  array (
    'a56eed4b8e746507e9190b54e73d579c6a448ab8' => 
    array (
      0 => 'wiki:Spray_common',
      1 => 20181124200749,
      2 => 'wiki',
    ),
  ),
  'includes' => 
  array (
  ),
),false)) {
function content_5d3837297acc10_49226086 ($_smarty_tpl) {
?>

<div class="wrap_itemnavi"><table><tbody>
<tr><th><a href="https://aionpowerbook.com/powerbook/Dagger"><img src="https://aionpowerbook.com/item/icon/icon_item_dagger_c01.png" width="25" height="25" alt=""><span>Dagger</span></a></th><td><a href="https://aionpowerbook.com/powerbook/Dagger_-_Mythical" class="mythic">Mythical</a><a href="https://aionpowerbook.com/powerbook/Dagger_-_Eternal" class="epic">Eternal</a><a href="https://aionpowerbook.com/powerbook/Dagger_-_Fabled" class="unique">Fabled</a><a href="https://aionpowerbook.com/powerbook/Dagger_-_Heroic" class="legend">Heroic</a></td></tr>
<tr><th><a href="https://aionpowerbook.com/powerbook/Sword"><img src="https://aionpowerbook.com/item/icon/icon_item_sword_c01.png" width="25" height="25" alt=""><span>Sword</span></a></th><td><a href="https://aionpowerbook.com/powerbook/Sword_-_Mythical" class="mythic">Mythical</a><a href="https://aionpowerbook.com/powerbook/Sword_-_Eternal" class="epic">Eternal</a><a href="https://aionpowerbook.com/powerbook/Sword_-_Fabled" class="unique">Fabled</a><a href="https://aionpowerbook.com/powerbook/Sword_-_Heroic" class="legend">Heroic</a></td></tr>
<tr><th><a href="https://aionpowerbook.com/powerbook/Mace"><img src="https://aionpowerbook.com/item/icon/icon_item_mace_c01.png" width="25" height="25" alt=""><span>Mace</span></a></th><td><a href="https://aionpowerbook.com/powerbook/Mace_-_Mythical" class="mythic">Mythical</a><a href="https://aionpowerbook.com/powerbook/Mace_-_Eternal" class="epic">Eternal</a><a href="https://aionpowerbook.com/powerbook/Mace_-_Fabled" class="unique">Fabled</a><a href="https://aionpowerbook.com/powerbook/Mace_-_Heroic" class="legend">Heroic</a></td></tr>
<tr><th><a href="https://aionpowerbook.com/powerbook/Staff"><img src="https://aionpowerbook.com/item/icon/icon_item_staff_c01.png" width="25" height="25" alt=""><span>Staff</span></a></th><td><a href="https://aionpowerbook.com/powerbook/Staff_-_Mythical" class="mythic">Mythical</a><a href="https://aionpowerbook.com/powerbook/Staff_-_Eternal" class="epic">Eternal</a><a href="https://aionpowerbook.com/powerbook/Staff_-_Fabled" class="unique">Fabled</a><a href="https://aionpowerbook.com/powerbook/Staff_-_Heroic" class="legend">Heroic</a></td></tr>
<tr><th><a href="https://aionpowerbook.com/powerbook/Spellbook"><img src="https://aionpowerbook.com/item/icon/icon_item_book_c01.png" width="25" height="25" alt=""><span>Spellbook</span></a></th><td><a href="https://aionpowerbook.com/powerbook/Spellbook_-_Mythical" class="mythic">Mythical</a><a href="https://aionpowerbook.com/powerbook/Spellbook_-_Eternal" class="epic">Eternal</a><a href="https://aionpowerbook.com/powerbook/Spellbook_-_Fabled" class="unique">Fabled</a><a href="https://aionpowerbook.com/powerbook/Spellbook_-_Heroic" class="legend">Heroic</a></td></tr>
<tr><th><a href="https://aionpowerbook.com/powerbook/Orb"><img src="https://aionpowerbook.com/item/icon/icon_item_orb_c01.png" width="25" height="25" alt=""><span>Orb</span></a></th><td><a href="https://aionpowerbook.com/powerbook/Orb_-_Mythical" class="mythic">Mythical</a><a href="https://aionpowerbook.com/powerbook/Orb_-_Eternal" class="epic">Eternal</a><a href="https://aionpowerbook.com/powerbook/Orb_-_Fabled" class="unique">Fabled</a><a href="https://aionpowerbook.com/powerbook/Orb_-_Heroic" class="legend">Heroic</a></td></tr>
<tr><th><a href="https://aionpowerbook.com/powerbook/Greatsword"><img src="https://aionpowerbook.com/item/icon/icon_item_2hsword_c01.png" width="25" height="25" alt=""><span>Greatsword</span></a></th><td><a href="https://aionpowerbook.com/powerbook/Greatsword_-_Mythical" class="mythic">Mythical</a><a href="https://aionpowerbook.com/powerbook/Greatsword_-_Eternal" class="epic">Eternal</a><a href="https://aionpowerbook.com/powerbook/Greatsword_-_Fabled" class="unique">Fabled</a><a href="https://aionpowerbook.com/powerbook/Greatsword_-_Heroic" class="legend">Heroic</a></td></tr>
<tr><th><a href="https://aionpowerbook.com/powerbook/Polearm"><img src="https://aionpowerbook.com/item/icon/icon_item_polearm_c01.png" width="25" height="25" alt=""><span>Polearm</span></a></th><td><a href="https://aionpowerbook.com/powerbook/Polearm_-_Mythical" class="mythic">Mythical</a><a href="https://aionpowerbook.com/powerbook/Polearm_-_Eternal" class="epic">Eternal</a><a href="https://aionpowerbook.com/powerbook/Polearm_-_Fabled" class="unique">Fabled</a><a href="https://aionpowerbook.com/powerbook/Polearm_-_Heroic" class="legend">Heroic</a></td></tr>
<tr><th><a href="https://aionpowerbook.com/powerbook/Bow"><img src="https://aionpowerbook.com/item/icon/icon_item_bow_c01.png" width="25" height="25" alt=""><span>Bow</span></a></th><td><a href="https://aionpowerbook.com/powerbook/Bow_-_Mythical" class="mythic">Mythical</a><a href="https://aionpowerbook.com/powerbook/Bow_-_Eternal" class="epic">Eternal</a><a href="https://aionpowerbook.com/powerbook/Bow_-_Fabled" class="unique">Fabled</a><a href="https://aionpowerbook.com/powerbook/Bow_-_Heroic" class="legend">Heroic</a></td></tr>
<tr><th><a href="https://aionpowerbook.com/powerbook/Aether_Revolver"><img src="https://aionpowerbook.com/item/icon/icon_item_gun_c01.png" width="25" height="25" alt=""><span>Aether Revolver</span></a></th><td><a href="https://aionpowerbook.com/powerbook/Aether_Revolver_-_Mythical" class="mythic">Mythical</a><a href="https://aionpowerbook.com/powerbook/Aether_Revolver_-_Eternal" class="epic">Eternal</a><a href="https://aionpowerbook.com/powerbook/Aether_Revolver_-_Fabled" class="unique">Fabled</a><a href="https://aionpowerbook.com/powerbook/Aether_Revolver_-_Heroic" class="legend">Heroic</a></td></tr>
<tr><th><a href="https://aionpowerbook.com/powerbook/Aether_Cannon"><img src="https://aionpowerbook.com/item/icon/icon_item_cannon_c01.png" width="25" height="25" alt=""><span>Aether Cannon</span></a></th><td><a href="https://aionpowerbook.com/powerbook/Aether_Cannon_-_Mythical" class="mythic">Mythical</a><a href="https://aionpowerbook.com/powerbook/Aether_Cannon_-_Eternal" class="epic">Eternal</a><a href="https://aionpowerbook.com/powerbook/Aether_Cannon_-_Fabled" class="unique">Fabled</a><a href="https://aionpowerbook.com/powerbook/Aether_Cannon_-_Heroic" class="legend">Heroic</a></td></tr>
<tr><th><a href="https://aionpowerbook.com/powerbook/Stringed_Instrument"><img src="https://aionpowerbook.com/item/icon/icon_item_harp_c01.png" width="25" height="25" alt=""><span>Stringed Instrument</span></a></th><td><a href="https://aionpowerbook.com/powerbook/Stringed_Instrument_-_Mythical" class="mythic">Mythical</a><a href="https://aionpowerbook.com/powerbook/Stringed_Instrument_-_Eternal" class="epic">Eternal</a><a href="https://aionpowerbook.com/powerbook/Stringed_Instrument_-_Fabled" class="unique">Fabled</a><a href="https://aionpowerbook.com/powerbook/Stringed_Instrument_-_Heroic" class="legend">Heroic</a></td></tr>
<tr><th><a href="https://aionpowerbook.com/powerbook/Aether_Key"><img src="https://aionpowerbook.com/item/icon/icon_item_keyblade_c01.png" width="25" height="25" alt=""><span>Aether Key</span></a></th><td><a href="https://aionpowerbook.com/powerbook/Aether_Key_-_Mythical" class="mythic">Mythical</a><a href="https://aionpowerbook.com/powerbook/Aether_Key_-_Eternal" class="epic">Eternal</a><a href="https://aionpowerbook.com/powerbook/Aether_Key_-_Fabled" class="unique">Fabled</a><a href="https://aionpowerbook.com/powerbook/Aether_Key_-_Heroic" class="legend">Heroic</a></td></tr>
<tr><th><a href="https://aionpowerbook.com/powerbook/Spray"><img src="https://aionpowerbook.com/item/icon/icon_item_spray_c01.png" width="25" height="25" alt=""><span>Spray</span></a></th><td><a href="https://aionpowerbook.com/powerbook/Spray_-_Mythical" class="mythic">Mythical</a><a href="https://aionpowerbook.com/powerbook/Spray_-_Eternal" class="epic">Eternal</a><a href="https://aionpowerbook.com/powerbook/Spray_-_Fabled" class="unique">Fabled</a><a href="https://aionpowerbook.com/powerbook/Spray_-_Heroic" class="legend">Heroic</a></td></tr>
</tbody></table></div><?php }
}
